### ISSUE TITLE
 unknown shorthand flag: 'M' in -MYSQL_ACCOUNTSANDCHARS=1

### ISSUE THREAD

**Issue by lehronn** [cmilanf/docker-rathena#2]
unknown shorthand flag: 'M' in -MYSQL_ACCOUNTSANDCHARS=1

error after run command. i using podman instead docker.

any ideas about that?? :(

**Comment by cmilanf** [comment]
Thanks for the notification, it was a typo as that is an environment variable that should be passed by the docker command line with `-e MYSQL_ACCOUNTSANDCHARS=1`. It has been corrected in 76c0838a863c463eb05b22fae542f1a315f55506.
